"""Optional ML training script for CMAPSS (baseline ridge regression).

This repository's primary goal is a dashboard-ready extract generated by
`src/prepare_cmapss.py`. If you want to extend the project with an ML model,
this file provides a small baseline trainer that uses only NumPy/Pandas.


Model
-----
A simple ridge regression on engineered features to predict `rul`.
This is intentionally minimal (no scikit-learn dependency).

Usage
-----
python src/train.py --train-path train_FD001.txt/train_FD001.txt --out-model data/models/rul_ridge.npz
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd


import feature_engineering as fe
import preprocessing as pp


@dataclass(frozen=True)
class RidgeModel:
    feature_names: list[str]
    coef: np.ndarray  # shape (n_features,)
    intercept: float
    x_mean: np.ndarray  # shape (n_features,)
    x_std: np.ndarray  # shape (n_features,)


def _standardize_matrix(X: np.ndarray, eps: float = 1e-12) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    mean = X.mean(axis=0)
    std = X.std(axis=0)
    std = np.where(std > eps, std, 1.0)
    return (X - mean) / std, mean, std


def train_ridge_regression(X: np.ndarray, y: np.ndarray, l2: float = 1.0) -> tuple[np.ndarray, float]:
    """Fit ridge regression with an intercept.

    Minimizes: ||Xw + b - y||^2 + l2 * ||w||^2

    Returns (w, b).
    """

    if X.ndim != 2:
        raise ValueError("X must be 2D")
    if y.ndim != 1:
        raise ValueError("y must be 1D")
    if X.shape[0] != y.shape[0]:
        raise ValueError("X and y row counts must match")

    # Center y for stable intercept estimation
    y_mean = float(y.mean())
    y_centered = y - y_mean

    n_features = X.shape[1]
    XtX = X.T @ X
    reg = l2 * np.eye(n_features, dtype=float)
    w = np.linalg.solve(XtX + reg, X.T @ y_centered)

    # With standardized X and centered y, intercept = y_mean
    b = y_mean
    return w, b


def save_model(model: RidgeModel, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        path,
        feature_names=np.array(model.feature_names, dtype=object),
        coef=model.coef,
        intercept=np.array([model.intercept], dtype=float),
        x_mean=model.x_mean,
        x_std=model.x_std,
    )


def load_model(path: Path) -> RidgeModel:
    data = np.load(path, allow_pickle=True)
    feature_names = data["feature_names"].tolist()
    coef = data["coef"].astype(float)
    intercept = float(data["intercept"][0])
    x_mean = data["x_mean"].astype(float)
    x_std = data["x_std"].astype(float)
    return RidgeModel(feature_names=feature_names, coef=coef, intercept=intercept, x_mean=x_mean, x_std=x_std)


def build_training_frame(train_path: Path, rolling_window: int = 5) -> pd.DataFrame:
    df = pp.read_cmapss_table(train_path)
    df = pp.add_train_rul(df)

    # Ensure correct order for rolling features
    df = df.sort_values(["unit", "cycle"], kind="mergesort")
    df = fe.add_rolling_features(df, window=rolling_window)
    return df


def train_from_path(train_path: Path, l2: float = 10.0, rolling_window: int = 5) -> RidgeModel:
    df = build_training_frame(train_path, rolling_window=rolling_window)

    y = pd.to_numeric(df["rul"], errors="coerce").fillna(0.0).to_numpy(dtype=float)

    fm = fe.to_feature_matrix(df)
    X_std, x_mean, x_std = _standardize_matrix(fm.X)

    w, b = train_ridge_regression(X_std, y, l2=l2)

    return RidgeModel(
        feature_names=fm.feature_names,
        coef=w,
        intercept=b,
        x_mean=x_mean,
        x_std=x_std,
    )


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Train a baseline ridge regression model to predict RUL")
    p.add_argument(
        "--train-path",
        type=Path,
        default=Path("train_FD001.txt/train_FD001.txt"),
        help="Path to CMAPSS train file. Default: train_FD001.txt/train_FD001.txt",
    )
    p.add_argument(
        "--out-model",
        type=Path,
        default=Path("data/models/rul_ridge.npz"),
        help="Where to write the trained model. Default: data/models/rul_ridge.npz",
    )
    p.add_argument("--l2", type=float, default=10.0, help="Ridge regularization strength. Default: 10.0")
    p.add_argument("--rolling-window", type=int, default=5, help="Rolling window for feature engineering. Default: 5")
    return p


def main() -> None:
    args = build_arg_parser().parse_args()

    model = train_from_path(args.train_path, l2=args.l2, rolling_window=args.rolling_window)
    save_model(model, args.out_model)

    print(f"Wrote model -> {args.out_model}")
    print(f"Features: {len(model.feature_names)}")


if __name__ == "__main__":
    main()
